# Generated by Django 5.1.6 on 2025-02-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_owner_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../nobody_dsnddu', upload_to='images/'),
        ),
    ]
