# Generated by Django 3.2.4 on 2025-02-18 13:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='/nobody_dsnddu.jpg', max_length=255, verbose_name='image'),
        ),
    ]
