# Generated by Django 5.1.3 on 2024-12-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stack', '0004_streakandmilestonetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='streakandmilestonetracker',
            name='milestone_dates',
            field=models.JSONField(default=list),
        ),
    ]
