# Generated by Django 5.1.3 on 2024-12-17 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stack', '0005_streakandmilestonetracker_milestone_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitstacking',
            name='active_until',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
