# Generated by Django 5.1.3 on 2024-12-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stack', '0007_milestonepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonepost',
            name='shared_on_feed',
            field=models.BooleanField(default=False),
        ),
    ]
