# Generated by Django 5.1.3 on 2025-01-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stack', '0008_milestonepost_shared_on_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitstacking',
            name='goal',
        ),
    ]
